version: '3.8'

services:
  py_executor:
    build: .
    container_name: py_executor
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    environment:
      - ENVIRONMENT=development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]