FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir selenium

COPY . .

COPY .env .

CMD ["flask", "run", "--host=0.0.0.0"]
